apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheus.hyperledger.org
spec:
  group: hyperledger.org
  names:
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheus
    singular: prometheus
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Prometheus is the Schema for the prometheus API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PrometheusSpec defines the desired state of Prometheus
            type: object
          status:
            description: PrometheusStatus defines the observed state of Prometheus
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
